### ISSUE TITLE
Allow reordering of conversion units

### ISSUE THREAD

**Issue by riverofjanuary** [ThiBsc/UnitsTool#8]
Love this tool and one of the few I've found that works in the UI I like.

I would love to be able to reorder the conversion units. I understand now they're ordered by size (for example mm/cm/m/km) but for my use case I would love mm/cm/in/feet to be first under the input box. Any way to add a drag n drop to be able to do this. Thank you.

**Comment by ThiBsc** [comment]
Hello @riverofjanuary Thank you for your feedback, I can add this feature, but I can't promise to be quick.
To know where to update the app, can you tell me if you use it from Google Play Store or from the FDroid store ?

**Comment by riverofjanuary** [comment]
Hi! Thanks for the quick response. F-Droid.

**Comment by ThiBsc** [comment]
Ok, here a first draft, it's just the visual result but the feature is far from end.
![Peek 10-04-2024 21-48](https://github.com/ThiBsc/UnitsTool/assets/9695045/6831da34-6c2a-49a8-bf01-c33d9ca16880)'

If you like the result tell me and I'll go with it to implement the reorder behavior

**Comment by riverofjanuary** [comment]
That's perfect! So if I stop dragging and drop (eg km above m in your example), it would remain there permanently, until I redragged (or maybe you want to make a "reset all" button)?  

On top of this: can it please remember the state somewhere in the app so if I close/reboot phone/etc it maintains that position?

Thank you again!

**Comment by ThiBsc** [comment]
Hello,
For the behavior, what I have in mind is indeed to store the order in a state to keep it over each close/reboot of the phone/app.
But if in an update I add a unit in a category, I'll reset the order with the default order because I don't want to deal with missing or non matching size/unit key etc.

But new unit is not at each update so it will be still userfirendly.
What do you think ?

**Comment by riverofjanuary** [comment]
I think that's great and makes perfect sense. Thank you for being so open!

**Comment by ThiBsc** [comment]
The feature is done and published to the Google Play store, but to update the FDroid store, I have to update a file on their repo because since the 1.0.10, I updated the version to fix some security issues.
The process to compile is a little bit different with this newer version of react native so I need to update the yaml on fdroid repo before tag the source code as 1.0.11 (I need to remember how to do it and the process is not only depending on me so it can be a delay).
If you want this feature quickly, you still can use the app from the Google store.
I let the issue open while the fdroid is not updated because you are using it so I can't consider it as done.
Thank you again to using the app, I have no statistics about utilisation on FDroid so I'm happy to see that some people use it

**Comment by riverofjanuary** [comment]
Thank you! I did get it originally through fdroid but can do google if necessary. Hope youre well :-)

**Comment by ThiBsc** [comment]
Issue open on fdroid to track and know how to update correctly the apk with the new version of node need by react and avoid generating a failed apk on fdroid
https://gitlab.com/fdroid/fdroiddata/-/issues/3244

**Comment by riverofjanuary** [comment]
You rock!

**Comment by ThiBsc** [comment]
The v1.0.11 is now available on FDroid store and the APK is working on my phone, I consider this issue as solved.
Don't hesitate if you have other ideas

**Comment by riverofjanuary** [comment]
Thank you!
